packages:
  - apps/*
  - packages/*
  - adapters/*
  - plugins/*
  - extensions/*

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - vite@8.2.2
