import sharp from "sharp";
import { describe, expect, it } from "vitest";
import { generateErrorTile, generateTransparentTile } from "./errorTile.js";

const coordinate = { zoom: 10, x: 549, y: 335 };

describe("error tile generation", () => {
  it.each([256, 512] as const)(
    "generates a diagonally striped %i px PNG for cache misses",
    async (tileSize) => {
      const tile = await generateErrorTile({
        type: "no_cache",
        tileSize,
        ...coordinate,
      });
      const image = sharp(tile);

      await expect(image.metadata()).resolves.toMatchObject({
        format: "png",
        width: tileSize,
        height: tileSize,
      });
      const { data, info } = await image
        .removeAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true });
      const colors = new Set<string>();
      for (let offset = 0; offset < data.length; offset += info.channels) {
        colors.add(`${data[offset]},${data[offset + 1]},${data[offset + 2]}`);
      }
      expect(colors).toContain("231,238,233");
      expect(colors).toContain("166,196,181");
    },
  );

  it("reuses generated bytes from the in-memory cache", async () => {
    const first = await generateErrorTile({
      type: "no_cache",
      tileSize: 256,
      ...coordinate,
    });
    const second = await generateErrorTile({
      type: "no_cache",
      tileSize: 256,
      ...coordinate,
    });

    expect(second).toBe(first);
  });

  it("renders different coordinates into otherwise equal error Tiles", async () => {
    const first = await generateErrorTile({
      type: "no_cache",
      tileSize: 256,
      ...coordinate,
    });
    const second = await generateErrorTile({
      type: "no_cache",
      tileSize: 256,
      ...coordinate,
      x: coordinate.x + 1,
    });

    expect(second).not.toEqual(first);
  });

  it("keeps the hatch phase seamless across tile boundaries", async () => {
    const small = await sharp(
      await generateErrorTile({
        type: "no_cache",
        tileSize: 256,
        ...coordinate,
      }),
    )
      .removeAlpha()
      .raw()
      .toBuffer();
    const large = await sharp(
      await generateErrorTile({
        type: "no_cache",
        tileSize: 512,
        ...coordinate,
      }),
    )
      .removeAlpha()
      .raw()
      .toBuffer();

    let mismatchedEdge: string | null = null;
    for (let y = 0; y < 64 && mismatchedEdge === null; y += 1) {
      const smallOffset = y * 256 * 3;
      const largeOffset = y * 512 * 3;
      const expected = small.subarray(smallOffset, smallOffset + 256 * 3);
      for (let x = 0; x < 2; x += 1) {
        const actualOffset = largeOffset + x * 256 * 3;
        if (
          !large.subarray(actualOffset, actualOffset + 256 * 3).equals(expected)
        ) {
          mismatchedEdge = `horizontal:${y}`;
          break;
        }
      }
    }
    for (let y = 0; y < 512 && mismatchedEdge === null; y += 1) {
      const smallOffset = (y % 256) * 256 * 3;
      const largeOffset = y * 512 * 3;
      if (
        !large
          .subarray(largeOffset, largeOffset + 48 * 3)
          .equals(small.subarray(smallOffset, smallOffset + 48 * 3))
      ) {
        mismatchedEdge = `vertical:${y}`;
      }
    }
    expect(mismatchedEdge).toBeNull();
  });

  it.each([256, 512] as const)(
    "generates a transparent %i px PNG for overlay cache misses",
    async (tileSize) => {
      const image = sharp(await generateTransparentTile(tileSize));
      await expect(image.metadata()).resolves.toMatchObject({
        format: "png",
        width: tileSize,
        height: tileSize,
        hasAlpha: true,
      });
      const { data, info } = await image.raw().toBuffer({
        resolveWithObject: true,
      });
      expect(info.channels).toBe(4);
      expect(data.every((channel) => channel === 0)).toBe(true);
    },
  );
});
